import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Corrected import to use Inter font
import "./globals.css";
import Header from "./components/Header";

// Initialize the Inter font
const inter = Inter({
  subsets: ["latin"],
  display: "swap", // Recommended for better performance
  variable: "--font-inter", // Optional: to use with CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Inter font to the body */}
      <body className={`${inter.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}