import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LoaderWrapper from "./components/ui/LoaderWrapper";

// Initialize Inter font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Tokeyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image" href="/fader.png" />
      </head>
      <body className={`${inter.className} antialiased`}>
        <LoaderWrapper/>
          <Header />
          {children}
          <Footer />
        
      </body>
    </html>
  );
}
